### ISSUE TITLE
Add "Update Gradle Wrapper Action"

### ISSUE THREAD

**Issue by koppor** [mnlipp/jdrupes-taglets#3]
To automatically follow the latest releases of Gradle, I would propose to install the [Update Gradle Wrapper Action](https://github.com/gradle-update/update-gradle-wrapper-action#update-gradle-wrapper-action).

It is as simple as adding another GitHub action. However, there [needs to be a repo-token generated](https://github.com/gradle-update/update-gradle-wrapper-action#repo-token). Therefore, I did not submit a PR immediatly.

**Comment by koppor** [comment]
I will update gradle in a PR and also add this action as proposal.

**Comment by mnlipp** [comment]
In my experience, upgrading gradle makes the build fail. Therefore such a change should not happen automatically.
